---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: release
  image: node:13
  environment:
    NODE_ENV: gh-pages
  commands:
  - yarn install
  - yarn build

- name: publish
  image: plugins/gh-pages
  settings:
    username:
      from_secret: 199103044a3e5d69be62
    password:
      from_secret: a2408bc2378d3acbc4b2981c84427efb739e5e65
    pages_directory: dist